"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import Navbar from "@/components/Navbar";
import ThemeContext from "./Context/themetoogle";

const [theme, setTheme] = useState<string>("dark");

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${theme === "dark" ? "dark" : ""}`}
      >
        <ThemeContext.Provider value={{ theme, setTheme }}>
          <Navbar />
          {children}
        </ThemeContext.Provider>
      </body>
    </html>
  );
}